plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.16'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ex'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 코드 수정 후 저장 시 서버 자동 재실행
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // @Getter @Setter @RequiredArgsConstructor 등 자동 생성
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Thymeleaf 템플릿 엔진
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // Thymeleaf 레이아웃 상속 
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    // JPA (Entity, Repository 등)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // H2 DB
    runtimeOnly 'com.h2database:h2'

    // 유효성 검증 (@NotEmpty @Size 등 폼 데이터 검증)
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // Spring Security ( 로그인 / 로그아웃 / 권한 처리 )
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // 현장 작업용 QR 라벨 생성
    implementation 'com.google.zxing:core:3.5.3'

    // Thymeleaf 에서 sec:authorize 등 시큐리티 문법 사용
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
}


tasks.named('test') {
	useJUnitPlatform()
}
