package com.ex.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SchemaMigrationConfigTest {

    @Test
    void legacyStorefrontOrdersAreMigratedOnlyOnce()
            throws Exception {
        DriverManagerDataSource dataSource =
                new DriverManagerDataSource(
                        "jdbc:h2:mem:migration-"
                                + UUID.randomUUID()
                                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                        "sa",
                        "");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createLegacyAndIntegratedTables(jdbcTemplate);
        insertLegacyOrder(jdbcTemplate);

        SchemaMigrationConfig config =
                new SchemaMigrationConfig();
        var migration =
                config.migrateIntegratedOrderSchema(jdbcTemplate);

        migration.run();
        migration.run();

        assertEquals(
                1,
                jdbcTemplate.queryForObject(
                        "select count(*) from customer_order",
                        Integer.class));
        assertEquals(
                "SHOP",
                jdbcTemplate.queryForObject(
                        "select order_channel from customer_order",
                        String.class));
        assertEquals(
                Boolean.TRUE,
                jdbcTemplate.queryForObject(
                        "select inventory_committed "
                                + "from customer_order",
                        Boolean.class));
        assertEquals(
                1,
                jdbcTemplate.queryForObject(
                        "select count(*) from order_item",
                        Integer.class));
        assertEquals(
                1,
                jdbcTemplate.queryForObject(
                        "select count(*) "
                                + "from order_lot_allocations",
                        Integer.class));
        assertEquals(
                "CUSTOMER_ORDER",
                jdbcTemplate.queryForObject("""
                        select referenced.table_name
                        from information_schema.table_constraints fk
                        join information_schema.referential_constraints ref
                          on ref.constraint_schema = fk.constraint_schema
                         and ref.constraint_name = fk.constraint_name
                        join information_schema.table_constraints referenced
                          on referenced.constraint_schema =
                                 ref.unique_constraint_schema
                         and referenced.constraint_name =
                                 ref.unique_constraint_name
                        where fk.table_schema = 'PUBLIC'
                          and fk.table_name = 'ORDER_ITEM'
                          and fk.constraint_name =
                              'FK_ORDER_ITEM_CUSTOMER_ORDER'
                        """, String.class));
        assertEquals(
                "CUSTOMER_ORDER",
                jdbcTemplate.queryForObject("""
                        select referenced.table_name
                        from information_schema.table_constraints fk
                        join information_schema.referential_constraints ref
                          on ref.constraint_schema = fk.constraint_schema
                         and ref.constraint_name = fk.constraint_name
                        join information_schema.table_constraints referenced
                          on referenced.constraint_schema =
                                 ref.unique_constraint_schema
                         and referenced.constraint_name =
                                 ref.unique_constraint_name
                        where fk.table_schema = 'PUBLIC'
                          and fk.table_name = 'SHIPMENT'
                          and fk.constraint_name =
                              'FK_SHIPMENT_CUSTOMER_ORDER'
                        """, String.class));
    }

    private void createLegacyAndIntegratedTables(
            JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                create table customer_order (
                    order_id bigint generated by default
                        as identity primary key,
                    order_number varchar(40),
                    user_id bigint,
                    member_id bigint,
                    order_channel varchar(20),
                    payment_method varchar(30),
                    customer_name varchar(40),
                    phone varchar(20),
                    recipient_name varchar(40),
                    recipient_phone varchar(20),
                    shipping_address varchar(200),
                    detail_address varchar(200),
                    unloading_location varchar(200),
                    delivery_request varchar(300),
                    product_amount numeric(38, 2),
                    delivery_fee numeric(38, 2),
                    total_price numeric(38, 2),
                    discount_price numeric(38, 2),
                    final_price numeric(38, 2),
                    regular_delivery boolean,
                    inventory_committed boolean,
                    status varchar(30),
                    created_at timestamp,
                    updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table purchase_order (
                    purchase_order_id bigint primary key,
                    order_number varchar(40),
                    member_id bigint,
                    customer_name varchar(40),
                    phone varchar(20),
                    address varchar(200),
                    detail_address varchar(200),
                    unloading_location varchar(200),
                    delivery_request varchar(300),
                    payment_method varchar(30),
                    status varchar(30),
                    product_amount integer,
                    delivery_fee integer,
                    discount_amount integer,
                    total_amount integer,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table purchase_order_item (
                    purchase_order_item_id bigint primary key,
                    purchase_order_id bigint,
                    product_id bigint,
                    product_name varchar(120),
                    quantity integer,
                    unit_price integer,
                    line_amount integer
                )
                """);
        jdbcTemplate.execute("""
                create table customer_order_copy_442_18 (
                    order_id bigint primary key
                )
                """);
        jdbcTemplate.execute("""
                create table order_item (
                    order_item_id bigint generated by default
                        as identity primary key,
                    order_id bigint,
                    product_id bigint,
                    product_name varchar(120),
                    quantity integer,
                    order_price numeric(38, 2),
                    line_amount numeric(38, 2),
                    lot_id bigint not null,
                    constraint customer_order_copy_442_18_fkgv4bnmo7
                        foreign key (order_id)
                        references customer_order_copy_442_18(order_id)
                )
                """);
        jdbcTemplate.execute("""
                create table order_lot_allocation (
                    order_lot_allocation_id bigint primary key,
                    purchase_order_item_id bigint,
                    product_lot_id bigint,
                    quantity integer,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table order_lot_allocations (
                    allocation_id bigint generated by default
                        as identity primary key,
                    order_item_id bigint,
                    product_lot_id bigint,
                    quantity integer,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table shipment (
                    shipment_id bigint generated by default
                        as identity primary key,
                    order_id bigint,
                    constraint customer_order_copy_442_18_fkshipment
                        foreign key (order_id)
                        references customer_order_copy_442_18(order_id)
                )
                """);
    }

    private void insertLegacyOrder(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.update("""
                insert into purchase_order values (
                    11,
                    'FF-LEGACY-001',
                    null,
                    '테스트 농장',
                    '010-1111-2222',
                    '충남 천안시',
                    '1번 창고',
                    '농장 입구',
                    '도착 전 연락',
                    'CARD',
                    'PAID',
                    30000,
                    5000,
                    0,
                    35000,
                    current_timestamp,
                    current_timestamp
                )
                """);
        jdbcTemplate.update("""
                insert into purchase_order_item values (
                    21,
                    11,
                    31,
                    '통합 테스트 사료',
                    2,
                    15000,
                    30000
                )
                """);
        jdbcTemplate.update("""
                insert into order_lot_allocation values (
                    41,
                    21,
                    51,
                    2,
                    current_timestamp,
                    current_timestamp
                )
                """);
    }
}
